name: Release-Auto-Pack
run-name: Packing Language Pack...
on:
  #[push]
  release:
    types: [published]
jobs:
  pack-all-files:
    name: Build & Pack Language Pack
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download latest csf translate file in INI format
        run: ./.github/scripts/download_latest_csf.cmd
        shell: cmd
      - name: Covent format to csf
        run: |
          ./.github/bin/CsfCoventer/CsfCoventer.exe "./ra2.csf.ini" "./ra2md.csf.ini"
      - name: Pack chinese audio to bag files
        run: |
          cd ./.github/scripts/pack-audio-bags
          npm i
          node index.js
      - name: Download & build ccmixar
        run: |
          git clone https://github.com/askeladdk/ccmixar.git
          cd ccmixar
          go build
      - name: Pack audio.mix & audiomd.mix
        run: |
          cd ccmixar
          ./ccmixar.exe pack -game ra2 -dir "../_src_files/audio" -mix "../_src_files/language/audio.mix"
          ./ccmixar.exe pack -game ra2 -dir "../_src_files/audiomd" -mix "../_src_files/langmd/audiomd.mix"
        shell: pwsh
      - name: Copy & pack cameo files
        run: |
          Copy-Item "./cameo/ra2/*" -Destination "./_src_files/cameo/" -Force
          Copy-Item "./cameo/ra2/*" -Destination "./_src_files/cameomd/" -Force
          ./ccmixar/ccmixar.exe pack -game ra2 -dir "./_src_files/cameo" -mix "./_src_files/language/audio.mix" -checksum -encrypt
          ./ccmixar/ccmixar.exe pack -game ra2 -dir "./_src_files/cameomd" -mix "./_src_files/langmd/audiomd.mix" -checksum -encrypt
        shell: pwsh
      - name: Copy there files cameo files
        run: |
          Copy-Item "./bik/ra2/*" -Destination "./_src_files/language/" -Force
          Copy-Item "./bik/yr/*" -Destination "./_src_files/langmd/" -Force
          Copy-Item "./credits/credits.txt" -Destination "./_src_files/language/" -Force
          Copy-Item "./credits/creditsmd.txt" -Destination "./_src_files/langmd/" -Force
          Copy-Item "./fnt/game.fnt" -Destination "./_src_files/language/" -Force
          Copy-Item "./shp/grfxtxt.shp" -Destination "./_src_files/language/" -Force
        shell: pwsh
      - name: Pack langeuage pack mix files
        run: |
          ./ccmixar/ccmixar.exe pack -game ra2 -dir "./_src_files/language" -mix "./language.mix" -checksum -encrypt
          ./ccmixar/ccmixar.exe pack -game ra2 -dir "./_src_files/langmd" -mix "./langmd.mix" -checksum
        shell: pwsh
      - name: Zip langeuage pack
        run: |
          7z a "RedAlert2-LanguagePack-ChineseSimplified.zip" subtitle\*
          7z a "RedAlert2-LanguagePack-ChineseSimplified.zip" language.mix
          7z a "RedAlert2-LanguagePack-ChineseSimplified.zip" langmd.mix
      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            RedAlert2-LanguagePack-ChineseSimplified.zip
