name: Release-Auto-Pack
run-name: Packing Language Pack...
on:
  [push]
  # registry_package:
  #  types: [published]
jobs:

  download-csf-files-and-covent:

    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download latest csf translate file in INI format
        run: ./.github/scripts/download_latest_csf.cmd
        shell: cmd
      - name: Covent format to csf
        run: |
          ./.github/bin/CsfCoventer/CsfCoventer.exe
          echo "./ra2.csf.ini"
          echo "./ra2md.csf.ini"
      - name: Update csf to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            ./ra2.csf
            ./ra2md/csf


