name: Release-Auto-Pack
run-name: Packing Language Pack...
on:
  [push]
  # release:
  #   types: [published]
jobs:
  pack-all-files:
    name: Build & Pack Language Pack
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download latest csf translate file in INI format
        run: ./.github/scripts/download_latest_csf.cmd
        shell: cmd
      - name: Covent format to csf
        run: |
          ./.github/bin/CsfCoventer/CsfCoventer.exe "./ra2.csf.ini" "./ra2md.csf.ini"
      - name: Pack chinese audio to bag files
        run: |
          cd ./.github/scripts/pack-audio-bags
          npm i
          node index.js
      - name: Download & build ccmixar
        run: |
          git clone https://github.com/askeladdk/ccmixar.git
          cd ccmixar
          go build
      - name: Pack audio.mix & audiomd.mix
        run: |
          cd ccmixar
          ./ccmixar.exe -game ra2 -dir "../_src_files/audio" -mix "../_src_files/language/audio.mix"
          ./ccmixar.exe -game ra2 -dir "../_src_files/audiomd" -mix "../_src_files/langmd/audiomd.mix"
        shell: cmd
      - name: Update csf to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            "./_src_files/language/audio.mix"
            "./_src_files/langmd/audiomd.mix"
